### ISSUE TITLE
There is no way to download an image file from list view

### ISSUE THREAD

**Issue by sergiocormio** [safrazik/vue-file-agent#39]
There is no way to download or open an image file from list view. When component is linkable and theme is "list view" all files can be downloaded except the image files: jpg, png, etc.
Only works on grid view theme.
Reproducible on live demo: https://safrazik.com/vue-file-agent/

**Comment by safrazik** [comment]
Thanks for reporting the issue. I was able to reproduce. It's a style related issue. Will be fixed in the next version.

Quick workaround until then:

```css
.theme-list .vue-file-agent .file-preview-wrapper .file-preview .thumbnail {
  z-index: 12;
}
```
