### ISSUE TITLE
Theming suport

### ISSUE THREAD

**Issue by The24thDS** [safrazik/vue-file-agent#6]
Any chance we will get some kind of them-ing features? Like to be able to change the background color using a prop

**Comment by safrazik** [comment]
Basic theming is supported is already available via `theme` property
> **theme** - When provided, a theme class is added to the container `.theme-<theme>`. Officially supported themes: `default` (grid view), `list` (list view)

In-detail theming is not available and it should be done with css.

If you want to change the gray background in list theme, you can do this:
```css
.theme-list .vue-file-agent .file-preview-wrapper .file-preview:before {
    background: #f2f2f2;
    border: 1px solid #bbb;
    border-left: 0;
}
```
I have plans to improve theming and css in general. A full refactor of css will be done in the future. And more theming will be supported via css classes.
